Update to requirements.txt for docker
PyNaCl is required to allow docker to work. With out PyNaCl you get the error output below.

When doing <docker build .> the change will allow PyNaCl to be added, preventing the error.

Tested on ubuntu 16.04.4 LTS 

[ERROR:bot] Unknown error attempting to connect to voice
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 456, in get_voice_client
    vc = await self.join_voice_channel(channel)
  File "/usr/src/musicbot/musicbot/bot.py", line 416, in join_voice_channel
    voice = discord.VoiceClient(**kwargs)
  File "/usr/lib/python3.6/site-packages/discord/voice_client.py", line 217, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice